export const elements = [
  {
    id: 1,
    pic_url: "../img/tours/1.webp",
    title: "Ocean Retreat + Dolphins",
    desc: "The deluxe version of Blue Safari provides any adventure and seafood enthusiast with a superior experience that will leave you captivated by Zanzibar's marine life and culinary delights. Starting with an early morning swim with dolphins, experience them swimming alongside you playfully in their natural environment. Take a swim in the hidden mangrove lagoon. Then continue on to one of the private islands of Pamunda to enjoy a mouth-watering, freshly prepared seafood bbq while quenching your thirst with a wide selection of alcoholic and non-alcoholic beverages and sampling the best fresh fruits Zanzibar has to offer.",
  },
  {
    id: 2,
    pic_url: "../img/tours/2.webp",
    title: "Dolphin Tour",
    desc: "An early morning well worth the experience. You will be taken to the fisherman’s village of Kizimkazi, on the South West side of the island. From there you will be taken out by motorboat beyond the breakers where the captain will search for the regularly frolicking pods of white dolphins and blue porpoises. You will be able to join them as they play in the waves and have a close encounter that will be an experience you will never forget.",
  },
  {
    id: 3,
    pic_url: "../img/tours/3.webp",
    title: "Ocean Retreat Safari",
    desc: "Sail, snorkel, swim, sunbathe, explore, feast, observe... The Blue Safari adventure is a day tour packed with several activities.",
  },
  {
    id: 4,
    pic_url: "../img/tours/4.webp",
    title: "Maalum Cave",
    desc: "This hidden gem provides all its visitors with a one-of-a-kind experience. Located just 5 minutes away from Jambiani Villas, Maalum cave is a beautifully kept natural swimming pool perfect for relaxing, swimming, and connecting with nature. Discover the cave by using the snorkeling gear provided by the establishment, listen to and observe the guide explaining its history and legends, and enjoy your time gazing at its wonderful and untouched environment.",
  },
  {
    id: 5,
    pic_url: "../img/tours/5.webp",
    title: "Snorkeling Blue Lagoon",
    desc: "The turquoise blue waters of the Indian Ocean spread along the coastline of Zanzibar. However, visiting the Blue Lagoon is much more than an incredible exploration of tropical fish and reefs. It is a place where you can swim with hundreds of fish and enjoy the diversity of underwater life. The Blue Lagoon excursion is tide-dependent, low tide is usually better for sight as its calm waters enhance the visibility of corals and fish, and also allow for an enjoyable swim!",
  },
  {
    id: 6,
    pic_url: "../img/tours/6.webp",
    title: "SKuza + Voodoo Cave",
    desc: "Kuza Cave is recognized as a sacred place to the forefathers of Jambiani residents. The ancient limestone cave was formed about 250,000 years ago by thousands of years of water erosion that created secret underground rivers and pools. Swimming in the healing mineral waters is an unforgettable experience. The villagers come to the Voodoo Cave to pray and burn incense as they believe their rituals call the spirits that aid in case of sickness or misfortune. Human and animal bones from 2000BC have been discovered in this cave.",
  },
  {
    id: 7,
    pic_url: "../img/tours/7.webp",
    title: "Snorkeling in Sunshine",
    desc: "For those who would like to go snorkeling and would like to avoid additional transportation, we have the perfect solution. Imagine the traditional boat (Ngalawa) arriving at the shore just in front of your villa taking you straight to the turquoise waters of the Indian Ocean. For a more thrilling experience, we will supply you with bread, so you can lure fish to the side of the boat. This excursion is dependent on the tide and wind. Therefore we kindly recommend placing requests in advance.",
  },
  {
    id: 8,
    pic_url: "../img/tours/8.webp",
    title: "Diving Experience",
    desc: "The stunning turquoise waters surrounding Zanzibar attract thousands of visitors from around the world each year, who consider this area one of the best diving spots in East Africa. The warm waters of the Indian Ocean are home to more than six hundred species of tropical fish, including parrotfish, clownfish, angelfish, butterfly fish, and trumpetfish! The rocks and reefs also provide shelter for moray eels and different species of crabs and octopi.",
  },
  {
    id: 9,
    pic_url: "../img/tours/9.webp",
    title: "Kayaking in Uzi Island",
    desc: "This four-hour excursion is the perfect choice for water sports and nature lovers. This green safari tour shows you a side of Zanzibar you didn't know existed! Kayak through the mangroves and observe wildlife from a completely new perspective. Stop on an island for a quick break and some fresh fruit. Take your kayak through bird islands and observe the undisturbed natural environment of a wild variety of local birds!",
  },
  {
    id: 10,
    pic_url: "../img/tours/10.webp",
    title: "Seaweed Center + The Rock",
    desc: "The Seaweed Center is a local company located in Paje, that produces handcrafted cosmetics from harvested seaweed. You will be shown the farm and planting techniques at the shore, walked through the sections of the factory, and later be able to visit the aroma treasury. All of the ecological products can be purchased at the in-house store. Enjoy a drink or two on an open-air terrace in The Rock restaurant, with panoramic sea scapes accompanied by a romantic feel under the African skies. Later move to the neighboring Upendo or Balladin, for a delicious feast.",
  },
  {
    id: 11,
    pic_url: "../img/tours/11.webp",
    title: "Jozani Forest",
    desc: "Take a trip with us to the environmentally protected Jozani Forest, also known as Jozani Chwaka Bay National Park. Jozani is the largest area of indigenous forest on Zanzibar Island. Situated south of Chwaka Bayonlow-lying land, the area is prone to flooding, which nurtures the lush swamp-like environment of moisture-loving trees and ferns. Here you will encounter the Red Colobus Monkey, an endangered species found only in Zanzibar, as well as other species of monkeys, bushbabies, duikers, and more than 40 species of birds.",
  },
  {
    id: 12,
    pic_url: "../img/tours/12.webp",
    title: "Snorkeling + The Rock + Sunset",
    desc: "The turquoise blue waters invite any aqua fanatics for a lovely exploration of tropical fish and reefs. The Blue Lagoon trip is tide-dependent, and we highly recommend going before low tide. This time is better for sight as its calm waters enhance the visibility of corals and fish, and also allow for an enjoyable swim! While on the Michamvi Peninsula you will get the opportunity to visit the world-famous The Rock restaurant and see the spectacular sunset from the hanging beds in Michamvi.",
  },
  {
    id: 13,
    pic_url: "../img/tours/13.webp",
    title: "Sunset Boat Cruise in Michamvi",
    desc: "About a 30 min drive from our hotel, you will board a boat that will take you to Chwaka Bay. Michamvi is one of the best places on the Eastern coast of Zanzibar to observe the spectacle of the setting sun disappearing into the Indian Ocean. You will get a chance to spend an evening watching the sky change from hues of orange into dyed pomegranate pink. There is a possibility to make a reservation for a private beach dinner in Michamvi Sunset Bay Resort - payment for dinner on the spot.",
  },
  {
    id: 14,
    pic_url: "../img/tours/14.webp",
    title: "Michamvi Sunset",
    desc: "This is a sunset you cannot miss! This jaw-dropping excursion begins with a visit to Kae Funk, a restaurant where you will be able to gaze at the dazzling colorful sky. Watch the sun slip away into the Indian Ocean with an array of orange and pink tones. Enjoy the calmness of the ocean and watch the sun set while relaxing with a delectable drink and good music.",
  },
  {
    id: 15,
    pic_url: "../img/tours/15.webp",
    title: "Mtende Secret Beach",
    desc: "Mtende Beach is the perfect destination for anyone fond of unique beaches and captivating views! This beach used to be a so-called secret beach - however, due to its mesmerizing scenery and surroundings, it has quickly gained popularity among tourists visiting the island. Enjoy the serenity and dazzling views while sipping on a cocktail or enjoying a delicious meal at Eden Rock or Usumba Rock Restaurant!",
  },
];
