export const elements = [
  {
    id: 1,
    pic_url: "../img/tours/1.webp",
    title: "Ocean Retreat + Dolphins",
    desc: "The deluxe version of Blue Safari provides any adventure and seafood enthusiast with a superior experience that will leave you captivated by Zanzibar's marine life and culinary delights",
  },
  {
    id: 2,
    pic_url: "../img/tours/2.webp",
    title: "Dolphin Tour",
    desc: "An early morning well worth the experience. You will be taken to the fisherman’s village of Kizimkazi, on the South West side of the island.",
  },
  {
    id: 3,
    pic_url: "../img/tours/3.webp",
    title: "Ocean Retreat Safari",
    desc: "Sail, snorkel, swim, sunbathe, explore, feast, observe... The Blue Safari adventure is a day tour packed with several activities.",
  },
  {
    id: 4,
    pic_url: "../img/tours/4.webp",
    title: "Maalum Cave",
    desc: "This hidden gem provides all its visitors with a one-of-a-kind experience. Located just 5 minutes away from Sunshine Villas",
  },
  {
    id: 5,
    pic_url: "../img/tours/5.webp",
    title: "Snorkeling Blue Lagoon",
    desc: "The turquoise blue waters of the Indian Ocean spread along the coastline of Zanzibar.",
  },
  {
    id: 6,
    pic_url: "../img/tours/6.webp",
    title: "SKuza + Voodoo Cave",
    desc: "Kuza Cave is recognized as a sacred place to the forefathers of Sunshine residents. ",
  },
  {
    id: 7,
    pic_url: "../img/tours/7.webp",
    title: "Snorkeling in Sunshine",
    desc: "For those who would like to go snorkeling and would like to avoid additional transportation, we have the perfect solution. ",
  },
  {
    id: 8,
    pic_url: "../img/tours/8.webp",
    title: "Diving Experience",
    desc: "The stunning turquoise waters surrounding Zanzibar attract thousands of visitors from around the world each year, who consider this area one of the best diving spots in East Africa.",
  },
  {
    id: 9,
    pic_url: "../img/tours/9.webp",
    title: "Kayaking in Uzi Island",
    desc: "This four-hour excursion is the perfect choice for water sports and nature lovers. ",
  },
  {
    id: 10,
    pic_url: "../img/tours/10.webp",
    title: "Seaweed Center + The Rock",
    desc: "The Seaweed Center is a local company located in Paje, that produces handcrafted cosmetics from harvested seaweed. ",
  },
  {
    id: 11,
    pic_url: "../img/tours/11.webp",
    title: "Jozani Forest",
    desc: "Take a trip with us to the environmentally protected Jozani Forest, also known as Jozani Chwaka Bay National Park.",
  },
  {
    id: 12,
    pic_url: "../img/tours/12.webp",
    title: "Snorkeling + The Rock + Sunset",
    desc: "The turquoise blue waters invite any aqua fanatics for a lovely exploration of tropical fish and reefs. The Blue Lagoon trip is tide-dependent, and we highly recommend going before low tide.",
  },
  {
    id: 13,
    pic_url: "../img/tours/13.webp",
    title: "Sunset Boat Cruise in Michamvi",
    desc: "About a 30 min drive from our hotel, you will board a boat that will take you to Chwaka Bay. Michamvi is one of the best places on the Eastern coast of Zanzibar to observe the spectacle of the setting sun disappearing into the Indian Ocean.",
  },
  {
    id: 14,
    pic_url: "../img/tours/14.webp",
    title: "Michamvi Sunset",
    desc: "This is a sunset you cannot miss! This jaw-dropping excursion begins with a visit to Kae Funk, a restaurant where you will be able to gaze at the dazzling colorful sky.",
  },
  {
    id: 15,
    pic_url: "../img/tours/15.webp",
    title: "Mtende Secret Beach",
    desc: "Mtende Beach is the perfect destination for anyone fond of unique beaches and captivating views! This beach used to be a so-called secret beach - however, due to its mesmerizing scenery and surroundings",
  },
];
